spring:
  application:
    name: Hotel
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12714941
    username: sql12714941
    password: k1RZFjnJcA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
servlet:
  multipart:
    file-size-threshold: 2KB
    max-request-size: 5MB
    max-file-size: 5MB
